name: Deploy to LS Dev VM

on:
  push:
    branches: ["feature/**", "change/**", "bugfix/**"]
    paths:
      - "logstash/**"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  LOGSTASH_VERSION: "8.13.4"

jobs:
  deploy:
    name: Deploy to LS Dev VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH and rsync
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_KEY_LS_DEV_VM }}" > "$HOME/.ssh/id_ed25519"
          chmod 600 "$HOME/.ssh/id_ed25519"
          cat > "$HOME/.ssh/config" << EOF
          Host target
            HostName ${{ secrets.SSH_HOST_LS_DEV_VM }}
            User ${{ secrets.SSH_USER_LS_DEV_VM }}
            Port ${{ secrets.SSH_PORT_LS_DEV_VM }}
            IdentityFile $HOME/.ssh/id_ed25519
            StrictHostKeyChecking no
          EOF

      - name: Deploy edge pipelines
        run: |
          rsync -e "ssh target" -avz --checksum \
            --exclude '99-output-to-rz.conf' \
            logstash/edge/pipelines/ \
            target:/opt/elk_dev/logstash/edge/pipelines/forwarder/

      - name: Deploy rz pipelines
        run: |
          rsync -e "ssh target" -avz --checksum \
            --exclude '99-output-es.conf' \
            logstash/rz/pipelines/ \
            target:/opt/elk_dev/logstash/rz/pipelines/rz/

      - name: Test configuration
        run: |
          ssh target '
            docker run --rm \
              -v /opt/elk_dev/logstash/edge/config:/usr/share/logstash/config \
              -v /opt/elk_dev/logstash/edge/pipelines/forwarder:/usr/share/logstash/pipeline \
              docker.elastic.co/logstash/logstash:${{ env.LOGSTASH_VERSION }} \
              --config.test_and_exit || { echo "Edge config invalid"; exit 1; }
            
            docker run --rm \
              -v /opt/elk_dev/logstash/rz/config:/usr/share/logstash/config \
              -v /opt/elk_dev/logstash/rz/pipelines/rz:/usr/share/logstash/pipeline \
              docker.elastic.co/logstash/logstash:${{ env.LOGSTASH_VERSION }} \
              --config.test_and_exit || { echo "RZ config invalid"; exit 1; }
          '