name: Test SSH to VM
on:
  workflow_dispatch:   # manueller Start im Actions-Tab

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_VM }}
          username: ${{ secrets.SSH_USER_VM }}
          key: ${{ secrets.SSH_KEY_VM }}
          script: |
            hostname
            whoami
            docker ps
