name: Test SSH to VM
on:
  workflow_dispatch:   # manueller Start im Actions-Tab

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
      - run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_KEY_VM }}") <<< "${{ secrets.SSH_PASSPHRASE_VM }}"
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST_LS_DEV_VM }}
          username: ${{ secrets.SSH_USER_LS_DEV_VM }}
          key: ${{ secrets.SSH_KEY_LS_DEV_VM }}
          port: ${{ secrets.SSH_PORT_LS_DEV_VM }}
          script: |
            hostname
            whoami
            docker ps
